# Generated by Django 5.0.2 on 2024-04-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='productlocation',
            name='product',
        ),
        migrations.DeleteModel(
            name='BusinessLocation',
        ),
        migrations.DeleteModel(
            name='ProductLocation',
        ),
    ]
