# Generated by Django 5.0.2 on 2024-02-10 14:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, max_length=300)),
                ('is_public', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2024, 2, 10, 14, 41, 58, 11650, tzinfo=datetime.timezone.utc))),
                ('date_updated', models.DateTimeField(default=datetime.datetime(2024, 2, 10, 14, 41, 58, 11650, tzinfo=datetime.timezone.utc))),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Business.business')),
            ],
        ),
    ]
