# Generated by Django 5.0.2 on 2024-04-21 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_location_remove_productlocation_product_and_more'),
        ('Product', '0002_alter_product_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Location.location'),
        ),
    ]
