# Generated by Django 5.0.2 on 2025-06-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0003_alter_location_latitude_alter_location_longitude'),
        ('Product', '0003_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Location.location'),
        ),
    ]
