# Generated by Django 5.0.2 on 2025-12-31 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
