# Generated by Django 5.0.2 on 2026-01-27 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Business', '0009_final_business_model_update'),
        ('Product', '0005_alter_product_date_updated'),
        ('QA', '0002_answercomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HowTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='A brief overview of what this process covers')),
                ('is_official', models.BooleanField(default=False, help_text='Marked by business owner as official documentation')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_tos', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='how_tos', to='Business.business')),
                ('origin_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='how_tos', to='QA.question')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='how_tos', to='Product.product')),
            ],
            options={
                'verbose_name': 'How To',
                'verbose_name_plural': "How To's",
                'ordering': ['-is_official', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HowToStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(help_text='Detailed instructions for this step')),
                ('image', models.ImageField(blank=True, null=True, upload_to='howto_steps/')),
                ('how_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='HowTo.howto')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
