# Generated by Django 5.0.2 on 2026-01-27 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HowTo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='howto',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='how_tos_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='howto',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='howto',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_tos_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HowToHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.CharField(blank=True, help_text='Optional description of what changed', max_length=255)),
                ('steps_snapshot', models.JSONField(default=list)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('how_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='HowTo.howto')),
            ],
            options={
                'verbose_name': 'How To History',
                'verbose_name_plural': 'How To Histories',
                'ordering': ['-version'],
            },
        ),
    ]
