# Generated by Django 5.0.2 on 2026-01-19 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_alter_notification_options_and_more'),
        ('QA', '0002_answercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='QA.question'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('price_change', 'Price Change'), ('price_drop', 'Price Drop'), ('comment_reply', 'Comment Reply'), ('new_comment', 'New Comment'), ('new_answer', 'New Answer')], max_length=20),
        ),
    ]
