# Generated by Django 5.0.2 on 2026-01-22 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0009_final_business_model_update'),
        ('Notification', '0003_notification_question_and_more'),
        ('Post', '0001_initial'),
        ('QA', '0002_answercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='QA.answer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Business.business'),
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Post.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('price_change', 'Price Change'), ('price_drop', 'Price Drop'), ('comment_reply', 'Comment Reply'), ('new_comment', 'New Comment'), ('new_answer', 'New Answer'), ('answer_accepted', 'Answer Accepted'), ('answer_comment', 'Answer Comment'), ('post_comment', 'Post Comment'), ('post_reply', 'Post Reply'), ('post_like', 'Post Like'), ('business_review', 'Business Review'), ('business_reply', 'Business Reply'), ('new_follower', 'New Follower')], max_length=20),
        ),
    ]
