# Generated by Django 5.0.2 on 2026-01-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0002_answercomment'),
        ('Tag', '0002_alter_tag_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='tags', to='QA.question'),
        ),
    ]
