# Generated by Django 5.0.2 on 2026-02-03 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HowTo', '0002_howto_last_editor_howto_version_alter_howto_author_and_more'),
        ('QA', '0002_answercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='howto_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='HowTo.howtostep'),
        ),
    ]
