# Generated by Django 5.0.2 on 2025-12-31 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0002_alter_producthistory_current_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
