# Generated by Django 5.0.2 on 2025-06-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_alter_business_description_alter_business_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude coordinate', null=True),
        ),
    ]
