# Generated by Django 5.0.2 on 2025-08-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0003_business_latitude_business_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='location_description',
            field=models.CharField(blank=True, help_text='Verbose description of the business location', max_length=200),
        ),
    ]
