# Generated by Django 5.0.2 on 2025-08-06 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0008_set_location_null'),
        ('Location', '0003_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ForeignKey(blank=True, help_text='GPS coordinates and address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Location.location'),
        ),
    ]
