# Generated by Django 5.0.2 on 2025-06-19 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_infocomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='infocomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='businesscomment',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='infocomment',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='productcomment',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='businesscomment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='infocomment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='slug',
        ),
        migrations.AddField(
            model_name='businesscomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesscomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='infocomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='infocomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='businesscomment',
            name='body',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='businesscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Comment.businesscomment'),
        ),
        migrations.AlterField(
            model_name='businesscomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='infocomment',
            name='body',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='infocomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Comment.infocomment'),
        ),
        migrations.AlterField(
            model_name='infocomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='body',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Comment.productcomment'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
