# Generated by Django 5.0.2 on 2025-12-31 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0003_alter_businesscomment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_%(class)s_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infocomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_%(class)s_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_%(class)s_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
