# Generated by Django 5.0.2 on 2025-12-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0004_businesscomment_likes_infocomment_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='infocomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='likes',
        ),
    ]
