# Generated by Django 5.0.2 on 2026-01-27 08:01

import Photo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=Photo.models.get_business_photo_filename),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=Photo.models.get_product_photo_filename),
        ),
    ]
